name: pandoc-minted
version: '0.0.2.0'
synopsis: A pandoc filter to render LaTeX code blocks using minted
category: Text
author: Eric Bailey
maintainer: eric@ericb.me
license: MIT
github: yurrriq/pandoc-minted
extra-source-files:
- CHANGELOG.md
dependencies:
- base >=4.8 && <5.0
- pandoc
- pandoc-types
executables:
  pandoc-minted:
    main: Main.lhs
